#!/usr/bin/env bash
SCRIPT_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))
[ ! -d "${SCRIPT_DIR}" ] && exit 100;

source "${SCRIPT_DIR}/../base"

# Package
PKG_DEB_FILE="${SCRIPT_DIR}/OpenTabletDriver.deb"
PKG_DEB_DSC="${SCRIPT_DIR}/opentabletdriver.dsc"

# Output

clean() {
  clean_target "${PKG_DEB_FILE}" "Cleaning up existing builds..."
  clean_target "${PKG_DEB_DSC}" "Cleaning up an existing debian control file..."
  clean_target "${SCRIPT_DIR}/debian/changelog" "Cleaning up an existing changelog file..."
  print "Cleaning up an opentabletdriver build folder..."
  find ${SCRIPT_DIR} -maxdepth 1 -name "opentabletdriver-*" -type d -exec rm -rf '{}' \;
  print "Removing other build results..."
  rm -f ${SCRIPT_DIR}/opentabletdriver_*
}

prepare() {
  pushd ${SCRIPT_DIR}
  cat <<EOF > debian/changelog
opentabletdriver (${PKG_VERSION}) UNRELEASED; urgency=low

  * New version: ${PKG_VERSION}

 -- InfinityGhost <infinityghostgit@gmail.com>  `LANG=C date +"%a, %d %b %Y %X %z"`
 
EOF

  make_debian_tarball "${SCRIPT_DIR}/opentabletdriver_${PKG_VERSION}.debian.tar.gz"
  make_source_tarball_with_linux_files "${SCRIPT_DIR}/opentabletdriver_${PKG_VERSION}.orig.tar.gz"  

  cat <<EOF > ${PKG_DEB_DSC}
Format: 3.0 (quilt)
Source: opentabletdriver
Version: ${PKG_VERSION}
Binary: opentabletdriver
Build-Depends: dotnet-sdk-6.0
Maintainer: InfinityGhost <infinityghostgit@gmail.com>, hwsnemo <hwsnemo@gmail.com>
Architecture: amd64
Standards-Version: 3.7.1
Files:
 `md5sum opentabletdriver_${PKG_VERSION}.orig.tar.gz | cut -d ' ' -f 1` `wc -c opentabletdriver_${PKG_VERSION}.orig.tar.gz`
 `md5sum opentabletdriver_${PKG_VERSION}.debian.tar.gz | cut -d ' ' -f 1` `wc -c opentabletdriver_${PKG_VERSION}.debian.tar.gz`
EOF
  popd
}

package() {
  create_debpkg "${PKG_DEB_FILE}"
  print "Packaging complete."
}

make_debian_tarball() {
  print "Making ${1} from debian tarball..."
  pushd "${SCRIPT_DIR}"
  tar -zcvf "${1}" "debian"
  popd
}

create_debpkg () {
  print "Packaging 'OpenTabletDriver.deb'..."
  pushd "${SCRIPT_DIR}"
  dpkg-source -x ${PKG_DEB_DSC}
  cd opentabletdriver-${PKG_VERSION}
  dpkg-buildpackage -rfakeroot -b
  cd ..
  mv "opentabletdriver_${PKG_VERSION}_amd64.deb" "${1}"
  popd
}

case $1 in
    "clean") clean ;;
    "prepare") prepare ;;
    "build") build ;;
    "package") package ;;
    *)
        clean
        prepare
        build
        package
    ;;
esac
