#!/usr/bin/env bash
SCRIPT_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))
[ ! -d "${SCRIPT_DIR}" ] && exit 100;

source "${SCRIPT_DIR}/../base"

# Package
PKG_RPM_FILE="${SCRIPT_DIR}/OpenTabletDriver.rpm"
SPEC_FILE="${SCRIPT_DIR}/opentabletdriver.spec"
RPM_TOPDIRS=(BUILD BUILDROOT RPMS SOURCES SPECS SRPMS)

# Output

clean() {
  clean_target "${PKG_RPM_FILE}" "Cleaning up existing builds..."

  for dir in ${RPM_TOPDIRS[@]}; do
    clean_target "${SCRIPT_DIR}/${dir}" "Cleaning up ${dir} folder..."
  done
}

prepare() {
  mkdir -p ${SCRIPT_DIR}/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
  make_source_tarball "${SCRIPT_DIR}/SOURCES/opentabletdriver-${PKG_VERSION}.tar.gz"
  make_linux_common_tarball "${SCRIPT_DIR}/SOURCES/opentabletdriver-common-${PKG_VERSION}.tar.gz"
}

package() {
  create_rpmpkg "${PKG_RPM_FILE}"
  print "Packaging complete."
}

create_rpmpkg() {
  print "Packaging 'OpenTabletDriver.rpm'..."
  rpmbuild -D "ver ${PKG_VERSION}" -D "_topdir ${SCRIPT_DIR}" -D "devel_package 1" -bb ${SPEC_FILE}
  mv ${SCRIPT_DIR}/RPMS/x86_64/opentabletdriver*.rpm ${1}
}

case $1 in
    "clean") clean ;;
    "prepare") prepare ;;
    "build") build ;;
    "package") package ;;
    *)
        clean
        prepare
        build
        package
    ;;
esac